### ISSUE TITLE
prettier_cli_path not being picked up

### ISSUE THREAD

**Issue by rogy** [jonlabelle/SublimeJsPrettier#32]
**Prettier version**
    1.1.0

**JsPrettier version** (package.json)
    "version": "1.7.4",

My Prettier.sublime-settings file looks like:

```
{
  "prettier_cli_path": "$HOME/.nvm/versions/node/v7.9.0/bin/prettier"
}
```

(which exists and executes fine)

however when running the installed plugin it get the following in the sublime console

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/callum.rogan/Library/Application Support/Sublime Text 3/Packages/sublime-prettier/prettier.py", line 67, in run
    prettify_code(edit, self.view, region)
  File "/Users/callum.rogan/Library/Application Support/Sublime Text 3/Packages/sublime-prettier/prettier.py", line 45, in prettify_code
    shell=IS_WINDOWS
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'prettier'
```

**Comment by jonlabelle** [comment]
The `$HOME` variable won't be automatically expanded. Also, you'll need to specify absolute paths when using NVM, for both `prettier_cli_path` and `node_path`.

**Comment by rogy** [comment]
@jonlabelle I had tried that also.

I get the exact same issue with my settings file being:

```
{
  "prettier_cli_path": "/Users/callum.rogan/.nvm/versions/node/v7.9.0/bin/prettier",
  "node_path": "/Users/callum.rogan/.nvm/versions/node/v7.9.0/bin/node"
}
```

**Comment by jlc467** [comment]
@rogy Try this:
```
{
  "node_path": ":/Users/myuser/.nvm/versions/node/v7.9.0/bin/"
}
```

**Comment by hundsim** [comment]
My problem was that I had installed it with Yarn. Problem solved by:

    yarn global remove prettier

And then install it with npm instead:

    npm install -g prettier

**Comment by JemarJones** [comment]
@hundsim I can confirm the same thing, this only seems to work when installed with npm.

**Comment by atefBB** [comment]
Hey @hundsim I use to install `prettier` globally with `npm` but still having the same issue.
Any ideas?

**Comment by jlc467** [comment]
@atefBB can you post your JsPrettier.sublime-settings ?

**Comment by atefBB** [comment]
@jlc467  this is my JsPrettier.sublime-settings file:
`{
	"debug": false,
	"prettier_cli_path": "C:/Users/.../AppData/Roaming/npm/prettier",
	"node_path": "C:/laragon/bin/nodejs/node-v6.11.0-x64/node.exe",
	"auto_format_on_save": false,
	"auto_format_on_save_excludes": [
		"*/node_modules/*",
		"*/.git/*"
	],
	"allow_inline_formatting": false,
	"custom_file_extensions": [],
	"max_file_size_limit": -1,
	"additional_cli_args": {},
	"prettier_options": {
		"printWidth": 80,
		"singleQuote": false,
		"trailingComma": "none",
		"bracketSpacing": true,
		"jsxBracketSameLine": false,
                "parser": "babylon",
		"semi": true,
		"requirePragma": false
	}
}`

**Comment by jlc467** [comment]
Have you tried leaving node_path and prettier_cli_path empty?

I would also try running `npm i prettier` inside the JsPrettier package folder (Sublime Preferences -> Browse Packages -> JsPrettier). JsPrettier will look there by default if you leave `prettier_cli_path` empty.

It would also help if you posted the exact error message you are getting.

**Comment by atefBB** [comment]
I do but the issue still occurs !

**Comment by tsai-jimmy** [comment]
The prettier DOC has this :
```
nvm users are required to set an appropriate absolute `prettier_cli_path`
(and absolute `node_path`), according to the target runtime environment.
```

Because we use nvm ,so we should setting absolute path that where node and prettier is.

 Open your terminal  and follow this command: 
`which node`
`which prettier`

![image](https://user-images.githubusercontent.com/18432952/35377271-74af6312-01e9-11e8-983c-0bf858156080.png)

**Comment by atefBB** [comment]
Hey, @tsai-jimmy I'm a Windows User! 
copy paths from `where node/prettier` to `prettier_cli_path`/`node_path` ?

**Comment by atefBB** [comment]
The issue still occurs after copying paths to `prettier_cli_path`/`node_path` !

**Comment by tsai-jimmy** [comment]
Can you upload your screenshot about the setting where you copy and Paste!
command : which node 
Next step : paste at `node_path`
```
{
  "prettier_cli_path": "/Users/myuser/.nvm/versions/node/v7.9.0/bin/prettier",
  "node_path": "past/your/path/to/node_path"
}
```
same as another

**Comment by tsai-jimmy** [comment]
Oh ! Are you used nvm to control  your node version?

**Comment by atefBB** [comment]
![node_prettier_cli_paths](https://user-images.githubusercontent.com/10966925/35388017-6af44df4-01d2-11e8-8070-977c94444a6c.png)

I don't use nvm to control node versions !

**Comment by tsai-jimmy** [comment]
Wait..
If you didn't use NVM ,so you didn't need to set  the absolute path.
which methods you installed  the plugin prettier before?
`npm insall` or use `package control : install package`

**Comment by atefBB** [comment]
@tsai-jimmy Did you mean that I should install `node` separately? `node` and `prettier` are already installed.

**Comment by tsai-jimmy** [comment]
hey, you set the node_path to blank
```
{
  "prettier_cli_path": "past/your/path",
  "node_path": ""
}
```
go to your javascript file ,run JsPrettier Format Code!
and  you also face this error? 
`FileNotFoundError: [Errno 2] No such file or directory: 'prettier'`

![image](https://user-images.githubusercontent.com/18432952/35430473-61eacbde-02b3-11e8-90e0-a0033e8f6a98.png)
okay, you should find the really path at prettier!

if you face this error `FileNotFoundError: [Errno 2] No such file or directory: 'node`
![image](https://user-images.githubusercontent.com/18432952/35430556-b97b4180-02b3-11e8-9ae9-368945469d23.png)
Okay, your prettier_cli_path has been correct! and find out your path to node!

I'm mac developer, because I face lots of  problem with windows before!
and I used NVM.
Sorry, I don't know what problems you truly faced...
but I recommend you to use NVM and you can manage your node and npm version!
Of course, manage where the position of plugin you use `npm` installed
,and your folder will be more clear !
At same  environment maybe we can resolves your problem!

this is my absolute path
![image](https://user-images.githubusercontent.com/18432952/35430671-4145db16-02b4-11e8-8e9a-9f3ceb50905b.png)

**Comment by tsai-jimmy** [comment]
oh  you can go to your sublime to open console!
`View/ show console`

**Comment by atefBB** [comment]
when I use this `"prettier_cli_path": "C:/Users/MyUserAccount/AppData/Roaming/npm/prettier.cmd",` the issue is gone !

**Comment by atefBB** [comment]
@tsai-jimmy thx for your help !

**Comment by tsai-jimmy** [comment]
@atefBB  yeah! great Job!

**Comment by jonlabelle** [comment]
See [solution](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).
